--- 
services: 
  basketapi: 
    build: 
      context: "."
      dockerfile: src/Basket/BasketApi/Dockerfile
    image: "${DOCKER_REGISTRY-}basketapi"
  basketdb: 
    image: redis
  catalogapi: 
    build: 
      context: "."
      dockerfile: src/Catalog/CatalogApi/Dockerfile
    image: "${DOCKER_REGISTRY-}catalogapi"
  catalogdb: 
    image: mongo
version: "3.4"
