--- 
services: 
  basketapi: 
    depends_on: 
      - basketdb
      - rabbitmq
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basketdb:6379"
      - "EventBus:HostName=rabbitmq"
    ports: 
      - "8001:80"
  basketdb: 
    container_name: basketdb
    ports: 
      - "6379:6379"
    restart: always
  catalogapi: 
    depends_on: 
      - catalogdb
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports: 
      - "8000:80"
  catalogdb: 
    container_name: catalogdb
    ports: 
      - "27017:27017"
    restart: always
  rabbitmq: 
    container_name: rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
    restart: always
version: "3.4"
