--- 
services: 
  basketapi: 
    build: 
      context: "."
      dockerfile: src/Basket/BasketApi/Dockerfile
    image: "${DOCKER_REGISTRY-}basketapi"
  basketdb: 
    image: redis
  catalogapi: 
    build: 
      context: "."
      dockerfile: src/Catalog/CatalogApi/Dockerfile
    image: "${DOCKER_REGISTRY-}catalogapi"
  catalogdb: 
    image: mongo
  orderdb: 
    image: mcr.microsoft.com/mssql/server
  orderingapi: 
    build: 
      context: "."
      dockerfile: src/Ordering/OrderingApi/Dockerfile
    image: "${DOCKER_REGISTRY-}orderingapi"
  rabbitmq: 
    image: "rabbitmq:3-management-alpine"
version: "3.4"
