--- 
services: 
  basketapi: 
    container_name: basketapi
    depends_on: 
      - basketdb
      - rabbitmq
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basketdb:6379"
      - "EventBus:HostName=rabbitmq"
    ports: 
      - "8001:80"
  basketdb: 
    container_name: basketdb
    ports: 
      - "6379:6379"
    restart: always
  catalogapi: 
    container_name: catalogapi
    depends_on: 
      - catalogdb
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports: 
      - "8000:80"
  catalogdb: 
    container_name: catalogdb
    ports: 
      - "27017:27017"
    restart: always
  orderdb: 
    container_name: orderdb
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: MyTestpassword!      
    ports: 
      - "1433:1433"
    restart: always
  orderingapi: 
    container_name: orderapi
    depends_on: 
      - orderdb
      - rabbitmq
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "OrderConnection:Server=orderdb;Database=OrderDb;User Id=sa;Password=MyTestpassword!;"
      - "EventBus:HostName=rabbitmq"
    ports: 
      - "8002:80"
    restart: on-failure
  rabbitmq: 
    container_name: rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
    restart: always
version: "3.4"
